version: '3'
services:
  api:
    container_name: api
    build: ./api
    ports:
      - "3333:3333"
    volumes:
      - ./api/src:/var/todo/src
    links:
      - mongodb
  application:
    container_name: application
    build: ./application
    ports:
      - "3000:3000"
    volumes:
      - ./application/src:/var/todo/src
    links:
      - api
  mongodb:
    container_name: mongodb
    image: mongo
    ports:
      - "27017:27017"
