version: '3'
services:
  api:
    build: ./api
    ports:
      - "3333:3333"
    volumes:
      - ./api:/var/todo/api/src
  application:
    build: ./application
    ports:
      - "3000:3000"
    volumes:
      - ./application:/var/todo/application/src
  mongodb:
    image: "mongo"
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ibrahim
      MONGO_INITDB_ROOT_PASSWORD: 123456
    ports:
      - "27017:27017"
